### ISSUE TITLE
windows support ?

### ISSUE THREAD

**Issue by zumoshi** [lrsjng/node-cgi#1]
it is a node only project (no native files) so should be cross platform , npm already creates a node-cgi.cmd file which allows running `node-cgi` from cmd , however 

```
To use it with an Apache httpd web server create a link to bin/node-cgi inside
your cgi-bin directory. 
```

part doesn't really work in windows . i tried to create a shortcut but apache says object not found for .nd files. (i'm on windows server 2003 so `mklink` is not an option)

so , how should i get it running with Xampp on win 2003 , that is if its doable at all.

tnx , bor.

**Comment by lrsjng** [comment]
I'm afraid I can't help you here. I don't have a windows machine to have a look it.. I'm sorry
